const prefix = 'LOGIN_DIALOG/'

export const DISP_LOADER = prefix + 'DISP_LOADER'
export const CHANGE_PHONE_NUMBER = prefix + 'CHANGE_PHONE_NUMBER'
export const CHANGE_CONFIRM_CODE = prefix + 'CHANGE_CONFIRM_CODE'
export const PHONE_NUMBER_SENT = prefix + 'PHONE_NUMBER_SENT'
export const SEND_CONFIRM_CODE = prefix + 'SEND_CONFIRM_CODE'
export const SIGNIN_ERROR = prefix + 'SIGNIN_ERROR'
export const GO_BACK = prefix + 'GO_BACK'
export const GO_CANCEL = prefix + 'GO_CANCEL'
