const prefix = 'SIGN_UP/'

export const SAVE_CREDIT_CARD = prefix + 'SAVE_CREDIT_CARD'
export const SAVE_FACE_PHOTO = prefix + 'SAVE_FACE_PHOTO'
export const SAVE_PHONE_NUMBER = prefix + 'SAVE_PHONE_NUMBER'
export const SEND_CONFIRM_CODE = prefix + 'SEND_CONFIRM_CODE'
export const RESET_CREDIT_CARD = prefix + 'RESET_CREDIT_CARD'
export const RESET_FACE_PHOTO = prefix + 'RESET_FACE_PHOTO'
export const SAVE_CREDIT_CARD_ERROR = prefix + 'SAVE_CREDIT_CARD_ERROR'
export const SAVE_FACE_PHOTO_ERROR = prefix + 'SAVE_FACE_PHOTO_ERROR'
export const SAVE_PHONE_NUMBER_ERROR = prefix + 'SAVE_PHONE_NUMBER_ERROR'
export const SEND_CONFIRM_CODE_ERROR = prefix + 'SEND_CONFIRM_CODE_ERROR'
